#ifndef __HTTP_CODES_H
#define __HTTP_CODES_H

typedef enum {
  Continue = 100,
  SwitchingProtocols,
  Processing,
  EarlyHints,

  OK = 200,
  Created,
  Accepted,
  NonAuthoritativeInfo,
  NoContent,
  ResetContent,
  PartialContent,
  MultiStatus,
  AlreadyReported,
  IMUsed = 226,

  MultipleChoices = 300,
  MovedPermanently,
  Found,
  SeeOther,
  NotModified,
  UseProxy,
  UNUSED ,
  TemporaryRedirect,
  PermanentRedirect,

  StatusBadRequest = 400,
  StatusUnauthorized,
  StatusPaymentRequired,
  StatusForbidden,
  StatusNotFound,
  StatusMethodNotAllowed,
  StatusNotAcceptable,
  StatusProxyAuthRequired,
  StatusRequestTimeout,
  StatusConflict,
  StatusGone,
  StatusLengthRequired,
  StatusPreconditionFailed,
  StatusRequestEntityTooLarge,
  StatusRequestURITooLong,
  StatusUnsupportedMediaType,
  StatusRequestedRangeNotSatisfiable,
  StatusExpectationFailed,
  StatusTeapot,
  StatusMisdirectedRequest = 421,
  StatusUnprocessableEntity,
  StatusLocked,
  StatusFailedDependency,
  StatusTooEarly,
  StatusUpgradeRequired,
  StatusPreconditionRequired = 428,
  StatusTooManyRequests,
  StatusRequestHeaderFieldsTooLarge = 431,
  StatusUnavailableForLegalReasons = 451,

  StatusInternalServerError = 500,
  StatusNotImplemented,
  StatusBadGateway,
  StatusServiceUnavailable,
  StatusGatewayTimeout,
  StatusHTTPVersionNotSupported,
  StatusVariantAlsoNegotiates,
  StatusInsufficientStorage,
  StatusLoopDetected,
  StatusNotExtended = 510,
  StatusNetworkAuthenticationRequired = 511
} http_status_code_t;

#endif // __HTTP_CODES_H